<?php

/**
 * OfertasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OfertasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OfertasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ofertas');
    }
}