<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/02/12 12:25:41

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=prueba',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
