<?php

/**
 * PluginOfertasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOfertasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOfertasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOfertas');
    }
}