generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ofertas
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ofertas
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      fields:
        id:                { label: Id }
        titulo:            { label: Titulo Oferta}
        texto:             { label: Descripcion}
        imagen:
          label:           Imagen
        fechainicio:       { label: Fecha Inicio,     params: date_format='dd/MM/yy' }
        fechafin:          { label: Fecha Fin Oferta, params: date_format='dd/MM/yy'}

      list:
        max_per_page:      2
        title:             Listado de Ofertas
        display:           [ =titulo, fechainicio, fechafin , imagen]
        fields:
          fechainicio:     { label: Inicio, params: date_format='dd/MM/yy' }
          fechafin:        { label: Fin,    params: date_format='dd/MM/yy' }
        actions:
#          _create:         ~
#		  { label: Crear Nueva Oferta }		  
      filter:
        display:           [ titulo, texto , fechainicio, fechafin ]
        #params:            <stong>%%=titulo%%<stong>, %%fechainicio%%
#        actions:
#          _create:         { name: Crear Nueva Oferta } ~

      form:
        actions:
          _create:         { label: Crear Nueva Oferta }
      edit:
        title:             Edici&oacute;n de Oferta de %%Titulo%%
        fields:
          fechainicio:     { params: date_format='dd/MM/yy' }
          fechafin:        { params: date_format='dd/MM/yy' }
          texto:           { type: textarea_tag, params: rich=true css=user.css tinymce_options=width:330 }
          imagen:
            type:          admin_input_file_tag
        actions:
          _delete:       { label: Eliminar Oferta }
          _list:         { label: Volver a la Lista }
          _save:         { label: Guardar Oferta }
          _save_and_add: { label: Guardar Oferta y Agregar Otra }

      new:
        title:             Crear Nueva Oferta.
        fields:
          fechainicio:     { params: date_format='dd/MM/yy' }
          fechafin:        { params: date_format='dd/MM/yy' }
          imagen:
            label:         Imagen
            help:          Ingrese una imagen JPG o PNG ()
            type:          admin_input_file_tag
            params:        include_link=imagenes include_remove=true
            upload_dir:    imagenes
            params:        include_link=imagenes include_remove=true
        actions:
          _list:           { label: Volver a la Lista }
          _save:           { label: Guardar Oferta }
          _save_and_add:   { label: Guardar Oferta y Agregar Otra }
